import { site } from "./site";

export const digitalShowreel = {
  title: "onvision",
  lead: "Sitios, tiendas y software a medida — a tu gusto, con Onvi IA incluido.",
  cta: {
    label: "Saber más",
    href: `https://wa.me/${site.whatsapp}?text=${encodeURIComponent("Hola, quiero una demo de Onvision Digital.")}`,
  },
  items: [
    {
      id: "web",
      label: "Sitios web",
      body: "Páginas web modernas que hacen que tu negocio destaque digitalmente.",
      poster: "/digital/web-pro-bafesa-cut2.png",
    },
    {
      id: "shop",
      label: "Tiendas en línea",
      body: "Catálogo, carrito, pagos online y panel admin. Con utilidades que las hacen únicas y personalizables.",
      poster: "/digital/ecom-firstdown-tienda-cut2.png",
    },
    {
      id: "saas",
      label: "Software a medida",
      body: "Paneles, reservas, inventario y flujos propios. Todo lo que tu operación necesite.",
      poster: "/digital/saas-clinicos-inventario-cut2.png",
    },
    {
      id: "mobile",
      label: "Apps móviles",
      body: "iOS y Android a medida cuando el negocio necesita estar en el bolsillo del cliente.",
      poster: "/digital/mobile-run-cut5.png",
    },
  ],
} as const;

export const digitalMeeting = {
  label: "02 — Agendar",
  title: "Agenda una reunión.",
  lead: "Elige fecha y hora y cuéntanos qué necesitas. Te confirmamos por correo o WhatsApp.",
  weekdays: ["D", "L", "M", "M", "J", "V", "S"],
  months: [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre",
  ],
  steps: {
    date: "Fecha",
    time: "Hora",
    service: "Servicio",
    details: "Tus datos",
  },
  timeLabel: "¿A qué hora?",
  /** De 9:00 a.m. a 9:00 p.m., cada hora (hora de Costa Rica). */
  times: [
    { label: "9:00 a.m.", hour: 9, minute: 0 },
    { label: "10:00 a.m.", hour: 10, minute: 0 },
    { label: "11:00 a.m.", hour: 11, minute: 0 },
    { label: "12:00 p.m.", hour: 12, minute: 0 },
    { label: "1:00 p.m.", hour: 13, minute: 0 },
    { label: "2:00 p.m.", hour: 14, minute: 0 },
    { label: "3:00 p.m.", hour: 15, minute: 0 },
    { label: "4:00 p.m.", hour: 16, minute: 0 },
    { label: "5:00 p.m.", hour: 17, minute: 0 },
    { label: "6:00 p.m.", hour: 18, minute: 0 },
    { label: "7:00 p.m.", hour: 19, minute: 0 },
    { label: "8:00 p.m.", hour: 20, minute: 0 },
    { label: "9:00 p.m.", hour: 21, minute: 0 },
  ],
  serviceLabel: "¿Qué quieres conversar?",
  services: [
    "Sitio web",
    "Tienda online",
    "Software a medida",
    "App móvil",
    "Consulta general",
  ],
  detailsLabel: "Tus datos",
  fields: {
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    phone: "Número",
    phonePlaceholder: "8888 8888",
    email: "Correo",
    emailPlaceholder: "hola@empresa.com",
    note: "Nota (opcional)",
    notePlaceholder: "Cuéntanos brevemente qué necesitas…",
  },
  submit: "Confirmar reunión",
  hint: "Lunes a viernes · hora de Costa Rica (GMT-6)",
} as const;

export const digitalPlans = {
  label: "02 — Precios",
  title: "Planes claros. Al alcance de tu negocio.",
  description:
    "Páginas web, tiendas, software y apps. Elige lo que necesitas, revisa qué incluye y paga mes a mes o en un solo pago.",
  period: "/ mes",
  yearLabel: "al año",
  yearSave: "ahorras 17%",
  onceLabel: "en un solo pago",
  /** Software y apps arrancan en ese precio y suben según el alcance. */
  fromLabel: "desde",
  mostChosen: "El más elegido",
  payMonthlyCta: "Empezar con este plan",
  paySheet: {
    title: "Continuar al pago",
    categorySeparator: " · ",
    monthlyLabel: "Mensualidad",
    companyNameLabel: "Nombre de tu empresa (opcional)",
    companyNamePlaceholder: "Ej. Mi negocio S.A.",
    note: "Vas a pagar la mensualidad con Onvo (tarjeta, SINPE y más). Si prefieres pagar una sola vez, escríbenos.",
    continueCta: "Pagar",
    continueLoading: "Abriendo el pago…",
    cancelCta: "Cancelar",
    closeAria: "Cerrar",
    errorGeneric: "No se pudo abrir el pago. Intenta de nuevo o escríbenos por WhatsApp.",
  },
  quoteCta: "Tengo una pregunta",
  /** Software y apps: primero se cotizan, después se paga. */
  meetingCta: "Agendar reunión",
  meetingHref: "#agendar",
  onceAskPrefix: "¿Prefieres pagar una sola vez?",
  onceAskLink: "Escríbenos",
  customQuotePrefix: "¿Tu proyecto necesita algo más?",
  customQuoteLink: "Pide una cotización a tu medida →",
  quoteHref: `https://wa.me/${site.whatsapp}?text=${encodeURIComponent("Hola, quiero cotizar un plan de Onvision Digital.")}`,
  /** Las pestañas (iguales al menú y al pie). */
  tabs: {
    web: "Páginas web",
    shop: "Tiendas en línea",
    software: "Software a medida",
    mobile: "Apps móviles",
  },
  /** La etiqueta sobre "Planes claros", según la pestaña. */
  eyebrows: {
    web: "Páginas web",
    shop: "Tiendas en línea",
    software: "Software",
    mobile: "Apps móviles",
  },
  groups: {
    web: {
      description:
        "Desde una página sencilla hasta un sitio completo con herramientas. Paga mes a mes o, si prefieres, en un solo pago.",
      plans: [
        {
          name: "Página estándar",
          tagline: "Para que tu negocio se vea profesional en internet.",
          price: "$35",
          priceAlt: "₡15.000",
          priceYear: "$350",
          priceFull: "$550",
          condition: "Mínimo 5 meses. Después cancelas cuando quieras.",
          checkoutId: "web-standard",
          features: [
            "Página de 1 a 3 secciones con tu marca",
            "Se ve perfecta en celular y computadora",
            "Botón de WhatsApp para recibir consultas",
            "Onvi, tu asistente con IA, atendiendo 24/7",
            "Dominio y hosting incluidos",
            "Aparece en Google desde el primer día",
            "Formulario de contacto y enlaces a tus redes",
            "Animaciones a la medida de tu marca",
            "Carga rápida, sin esperas",
            "Panel Onvi para ver mensajes y pedir cambios",
            "La publicamos por ti, sin costo extra",
            "Soporte y cambios pequeños incluidos cada mes",
          ],
        },
        {
          name: "Página Pro",
          tagline: "Para negocios que quieren vender, recibir reservas y crecer desde su página.",
          price: "$55",
          priceAlt: "₡25.000",
          priceYear: "$550",
          priceFull: "$750",
          condition: "Mínimo 5 meses. Después cancelas cuando quieras.",
          checkoutId: "web-pro",
          highlighted: true,
          includesPrevious: "Todo lo de Página estándar, más:",
          features: [
            "Sitio de varias páginas, hecho a medida",
            "Reservas, calculadoras, filtros o mapas",
            "Onvi entrenado con la información de tu empresa",
            "Blog o noticias que tú mismo actualizas",
            "Soporte prioritario y mejoras cada mes",
            "Animaciones e interacciones más elaboradas",
            "Estadísticas de visitas y formularios conectados",
            "Diseño pensado para convertir visitas en clientes",
            "Capacitación para que manejes tu página",
          ],
        },
      ],
    },
    shop: {
      description:
        "Vende por internet con tu catálogo, carrito y pagos en línea. Paga mes a mes o en un solo pago.",
      plans: [
        {
          name: "Tienda estándar",
          tagline: "Para empezar a vender en línea.",
          price: "$50",
          priceAlt: "₡22.000",
          priceYear: "$500",
          priceFull: "$750",
          condition: "Mínimo 5 meses. Después cancelas cuando quieras.",
          checkoutId: "shop-standard",
          features: [
            "Catálogo de productos con fotos y filtros",
            "Pedidos por WhatsApp o carrito de compras",
            "Cobros con tarjeta, transferencia o SINPE",
            "Aviso de cada pedido por correo o WhatsApp",
            "Panel para cambiar precios e inventario",
            "Se ve perfecta en celular y computadora",
            "Galería de fotos en cada producto",
            "Tus productos aparecen en Google",
            "Hosting, sitio seguro y soporte cada mes",
            "Carga rápida, sin esperas",
            "La publicamos por ti, sin costo extra",
            "Panel Onvi incluido",
            "Una ronda de cambios antes de publicar",
          ],
        },
        {
          name: "Tienda Pro",
          tagline: "Tu tienda completa, lista para crecer.",
          price: "$65",
          priceAlt: "₡30.000",
          priceYear: "$650",
          priceFull: "$950",
          condition: "Mínimo 5 meses. Después cancelas cuando quieras.",
          checkoutId: "shop-pro",
          highlighted: true,
          includesPrevious: "Todo lo de Tienda estándar, más:",
          features: [
            "Productos ilimitados, con tallas, colores y variantes",
            "Carrito y pago pensados para vender más",
            "Funciones a medida: armar outfits, filtrar por liga, personalizar productos",
            "Cupones y descuentos desde tu panel",
            "Reportes de ventas y estadísticas",
            "Soporte prioritario y mejoras cada mes",
            "Capacitación para que manejes tu tienda",
            "Dos rondas de cambios antes de publicar",
          ],
        },
      ],
    },
    software: {
      description:
        "Sistemas como ClinicOS, UniLearn o Sistema Gan, hechos para tu negocio. Paga mes a mes o pide una cotización.",
      /** Se cotiza primero: el botón principal es cotizar y el otro, agendar. */
      quoteCta: "Cotizar mi sistema",
      plans: [
        {
          name: "Software a medida",
          tagline: "Un sistema hecho para cómo trabaja tu negocio.",
          price: "$130",
          priceYear: "$1.300",
          priceFull: "$1.750",
          checkoutId: "software-saas",
          highlighted: true,
          badge: "Hecho a tu medida",
          startsAt: true,
          features: [
            "Módulos a tu medida: ventas, inventario, clientes, rutas y más",
            "Usuario y contraseña para cada persona de tu equipo",
            "Permisos por usuario y conexión con otras herramientas",
            "Panel de administración hecho para ti",
            "Reportes y gráficos que puedes descargar",
            "Cobros en línea, si tu negocio los necesita",
            "Avisos por correo y dentro del sistema",
            "Tus datos protegidos y cifrados",
            "En la nube: crece contigo sin cambiar de sistema",
            "Hosting, copias de seguridad y monitoreo 24/7",
            "Capacitación y manuales para tu equipo",
            "Soporte prioritario y mejoras continuas",
            "Panel Onvi incluido",
          ],
        },
      ],
    },
    mobile: {
      description: "Apps para iPhone y Android hechas a tu medida. Paga mes a mes o en un solo pago.",
      quoteCta: "Cotizar mi app",
      plans: [
        {
          name: "App móvil",
          tagline: "Tu negocio en el celular de tus clientes.",
          price: "$150",
          priceYear: "$1.500",
          priceFull: "$1.500",
          checkoutId: "mobile-app",
          highlighted: true,
          badge: "Hecha a tu medida",
          startsAt: true,
          features: [
            "App para iPhone y Android con tu marca",
            "Te ayudamos a publicarla en App Store y Google Play",
            "Pedidos, reservas o lo que tu negocio necesite",
            "Notificaciones al instante en el celular",
            "Registro, inicio de sesión y recuperar contraseña",
            "Diseño hecho a la medida de tus clientes",
            "Funciona sin internet y se actualiza al conectarse",
            "Conectada a tu sistema o panel de administración",
            "Pagos y suscripciones dentro de la app (si aplica)",
            "Estadísticas de uso y aviso de errores",
            "Enlaces para compartir productos o contenido",
            "Capacitación, manuales y soporte cada mes",
            "Panel Onvi incluido",
          ],
        },
      ],
    },
  },
} as const;

export type DigitalPlanGroupKey = keyof typeof digitalPlans.groups;

export const digitalFaq = {
  label: "01 — FAQ",
  title: "Lo que se pregunta todo el mundo antes de empezar",
  description:
    "Las dudas más comunes sobre la mensualidad, el dominio y qué pasa si querés parar.",
  itemPrefix: "FAQ-",
  items: [
    {
      q: "¿El sitio es mío o de ustedes?",
      a: "Tuyo. Con el pago único queda a tu nombre desde que se entrega. Con la mensualidad también es tuyo, mientras la mensualidad esté al día.",
    },
    {
      q: "Si elegís la mensualidad, ¿cuál es el mínimo antes de poder cancelar?",
      a: "En sitios web y tiendas, el mínimo son 5 meses. Después de eso podés cancelar en cualquier momento, e incluso pedir la devolución de esa mensualidad si la usaste menos de la mitad del mes. Software y apps móviles no tienen ese mínimo.",
    },
    {
      q: "¿Qué pasa si cancelo o me atraso con el pago?",
      a: "Tenés 5 días para ponerte al día antes de que se desactiven la página y los demás servicios. Tené en cuenta que la mensualidad no cubre solo la página web: incluye el mantenimiento, el pago del servicio de IA y tu espacio promocional en nuestro sitio.",
    },
    {
      q: "¿Qué cubre exactamente el soporte incluido?",
      a: "La mensualidad cubre dos cosas distintas. Por un lado, cambios sobre el sitio, que coordinamos según lo que vaya necesitando tu negocio:",
      groups: [
        {
          title: "Cambios sobre el sitio",
          points: [
            "Cambios de diseño y estructura según las necesidades del negocio.",
            "Creación y adición de nuevas secciones dentro de la página.",
            "Actualización de contenido, imágenes y elementos visuales.",
          ],
        },
        {
          title: "Y de forma ilimitada",
          points: [
            "Mantenimiento técnico y solución de errores o fallos que puedan presentarse.",
            "Atención ante posibles ataques cibernéticos o problemas de seguridad de la página.",
            "Supervisión general para mantener la página funcionando correctamente.",
          ],
        },
      ],
    },
    {
      q: "¿A nombre de quién queda el dominio?",
      a: "El dominio lo comprás vos y queda a tu nombre. Ronda los $11 al año (unos ₡5.000 colones). Nosotros lo dejamos comprado, configurado y apuntando a tu sitio.",
    },
    {
      q: "¿Cuánto tarda desde que pago?",
      a: "Depende bastante de qué tan rápido fluya la información de tu lado, porque el sitio es 100% personalizado. El tiempo promedio es de una semana: la idea es entregar de forma eficiente, sin bajarle a la calidad.",
    },
    {
      q: "Ya tengo página, ¿la pueden migrar?",
      a: "Sí, y sin ningún costo adicional.",
    },
    {
      q: "¿Por qué mensualidad y no un solo pago?",
      a: "La mensualidad se añadió para darle la oportunidad a los negocios de tener un servicio digital de manera más accesible. Aun así, podés elegir la que te sirva: el pago único aparece en cada plan.",
    },
  ],
  footerText: "¿Te quedó otra duda? ",
  footerCta: "Escribinos",
  footerHref: `https://wa.me/${site.whatsapp}?text=${encodeURIComponent("Hola, tengo una duda sobre Onvision Digital.")}`,
} as const;
